### ISSUE TITLE
A propose of signature context string

### ISSUE THREAD

**Issue by william-zk** [tlswg/tls-subcerts#63]
In draft-ietf-tls-subcerts-04 and later version, the signature context string change to `"TLS, server delegated credentials"`and `"TLS, client delegated credentials"`, and we found it will bring some problems in our practice.
In cloud native scenario, a service always corresponding to a fixed credential,  a service can be a server or a client at the same time. So we have to deploy two delegated credential in a service for mtls. That's really do harm to our credential manage but bring no security improvement.
Actually, similar context string in tls1.3 handshake(rfc 8446) is useful because of user can easily distinguish the behavior of client and server. And in our practice, there is no need to make a distinction between client and server in credential, the context string maybe can change to the same in client and server, format can like this `"TLS, handshake delegated credentials" `

**Comment by jhoyla** [comment]
In protocol design it is considered best practice to make sure that a cryptographic object can only have one meaning.
If a cryptographic object, in this case a certificate, can be used in different places with different meanings then it is possible that there will be confusion attacks. 
For example the [Selfie attack](https://eprint.iacr.org/2019/347.pdf) shows that reusing pre-shared keys (PSKs) for both clients and servers introduces an attack.
A lot of work goes into analysing protocols and checking they're secure. 
Making the client and server certificates have different types makes that analysis much easier and more robust.

Another advantage of this design is that it gives operators control of what DCs can be used for.
If an operator wanted to restrict the use of a DC to either client authentication or server authentication using the proposed scheme it would require setting either the TLS Web Server Authentication OID (OID.1.3.6.1.5.5.7.3.1) or the TLS Web Client Authentication OID (OID.1.3.6.1.5.5.7.3.2), but not both.
However a quick look at Certificate Transparency logs shows that most (~85%) of certificates do have both OIDs, this seems to be the default behaviour.
Thus the proposed design would in practice limit operators ability to secure systems.

**Comment by william-zk** [comment]
Thanks for your answering. I get your point, but it still have a question, should delegated credential have a filed to illustrate whether a delegated credential is used for client or server. It seems there are only two methods to make a distinguish
1. Verify signature, server side delegated credential can only pass verify processing with "TLS, server ...", same as client side.
2. Write some tag information in delegated credential storage file
methods 1 is complicated, and cost mush more time than a illustration filed
methods 2 problem is that there is no standard way to illustrate how to save delegated as file(see my issue #62 ).
So will the next version draft give a method to solve the problem?

**Comment by jhoyla** [comment]
An illustrative field would have to be signed, because otherwise it would be trivial to turn a client certificate into a server certificate, and vice versa, which is insecure. If the field is signed you would still need to deploy two certificates to your endpoints. 
Simply saving a tag in the storage file doesn't help. The tag would need to be signed for security purposes, which would still require you to deploy two certificates. 

By including the string in the signature format we can be sure that implementors actually check whether the certificate is a client certificate or a server certificate, which helps reduce the risk of bugs in the software. Making protocol success dependent on performing all security checks means that implementors don't forget to include them, because their software won't work without them.

**Comment by william-zk** [comment]
Em...I think that the lack of tag would make the implementation of delegated credential(dc) become more complicated, Image that a procedure will be client and server at the same time, when I load a dc to memory, sometimes I have to verify dc signature twice (Loading client dc but use "TLS, server..."). A tag is very helpful to simplify this process, I can use the tag and corresponding context string to verify signature, and ensure verify processing only happens once. That would help developer to write cleaner and more robust code:-)
We will still include this tag to signature, make sure everything in dc  can't be tampered.

**Comment by grittygrease** [comment]
The suggestion (2) from @william-zk (Write some tag information in delegated credential storage file) seems to satisfy the requirements above and is something that can be managed at the application layer or file system layer (you can put the usage of the DC into the filename, for example). File management is out of scope for this document, so this issue seems safe to close.

If there is still a strong disagreement, please take this discussion to the tlswg mailing list so that consensus can be established.
