### ISSUE TITLE
Should sever abort connection when server dc SignatureScheme mismatch SignatureSchemeList in client dc extension?

### ISSUE THREAD

**Issue by william-zk** [tlswg/tls-subcerts#64]
Draft only said that: " If the extension is present, the server MAY send a delegated credential ".
Should sever abort connection when server dc SignatureScheme mismatch SignatureSchemeList in client dc extension? Or just ignore this extension？

**Comment by grittygrease** [comment]
Yes, if there's a mismatch the connection should be terminated.

From the text:

   The expected_cert_verify_algorithm field MUST be of a type advertised
   by the client in the SignatureSchemeList and is considered invalid
   otherwise.  Clients that receive invalid delegated credentials MUST
   terminate the connection with an "illegal_parameter" alert.
